var geom_8h =
[
    [ "vec2", "structvec2.html", null ],
    [ "vec", "structvec.html", null ],
    [ "vec4", "structvec4.html", null ],
    [ "quat", "structquat.html", null ],
    [ "dualquat", "structdualquat.html", null ],
    [ "matrix3", "structmatrix3.html", null ],
    [ "matrix4x3", "structmatrix4x3.html", null ],
    [ "plane", "structplane.html", null ],
    [ "triangle", "structtriangle.html", null ],
    [ "ivec", "structivec.html", null ],
    [ "ivec2", "structivec2.html", null ],
    [ "ivec4", "structivec4.html", null ],
    [ "bvec", "structbvec.html", null ],
    [ "bvec4", "structbvec4.html", null ],
    [ "svec", "structsvec.html", null ],
    [ "dvec4", "structdvec4.html", null ],
    [ "matrix4", "structmatrix4.html", null ],
    [ "matrix2", "structmatrix2.html", null ],
    [ "half", "structhalf.html", null ],
    [ "GenericVec2< T >", "structGenericVec2.html", null ],
    [ "GenericVec3< T >", "structGenericVec3.html", null ],
    [ "GenericVec4< T >", "structGenericVec4.html", null ],
    [ "squat", "structsquat.html", null ],
    [ "R", "geom_8h.html#ae991d89d766b25a0e9b0f07509128749", null ]
];