name: Makefile | g++

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        cpp_version: [20]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Update package list
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libglew-dev

    - name: Build
      run: make -C src CPP_VERSION=${{ matrix.cpp_version }} -j4

    - name: Upload libprimis.so artifact
      uses: actions/upload-artifact@v4
      with:
        name: libprimis-linux
        path: ./src/libprimis.so
